name: CI
on:
  push:
    branches:
      - develop
jobs:
  release:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Builds the app for production
        run: npm install && npm run build
      - name: Launches the test
        run: npm test
      - name: Launches ESlint
        run: npm run lint